services:
  app:
    build: .
    container_name: starsoft-api
    restart: unless-stopped
    ports:
      - "4000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://starsoft:starsoft123@postgres:5432/cinema_tickets?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6380
      KAFKA_BROKERS: kafka:29092
      PORT: 3000
    networks:
      - starsoft-network
    # Production command: Migrate -> Seed -> Start
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node dist/src/main"

  postgres:
    image: postgres:15-alpine
    container_name: starsoft-postgres
    restart: always
    environment:
      POSTGRES_USER: starsoft
      POSTGRES_PASSWORD: starsoft123
      POSTGRES_DB: cinema_tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U starsoft -d cinema_tickets" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - starsoft-network

  redis:
    image: redis:8.2.2
    container_name: starsoft-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - starsoft-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: starsoft-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - starsoft-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: starsoft-kafka
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - starsoft-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: starsoft-kafka-ui
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: starsoft-cinema
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8080:8080"
    networks:
      - starsoft-network

volumes:
  postgres_data:
  redis_data:


networks:
  starsoft-network:
    driver: bridge
